export const SELF_EVAL_QUERY = `
    What are the security best practices, common misconfigurations, code quality guidelines, and best practices for writing clear and maintainable Infrastructure as Code using Terraform, Ansible, and OpenStack for junior developers and beginners new to DevOps and IaC?
`

export const SELF_EVAL_SECURITY_QUERY = `
    What are the security vulnerabilities, misconfigurations, hardening guidelines, and security best practices for Infrastructure as Code using Terraform, Ansible, and OpenStack?
`

export const SELF_EVAL_CLEAN_CODE_QUERY = `
    What are the code quality guidelines, clean code principles, maintainability best practices, and recommended patterns for writing readable, maintainable, testable and well-structured Infrastructure as Code using Terraform, Ansible, and OpenStack?
`

export const SELF_EVAL_PROMPT = `
    You are a senior DevOps Engineer and expert in Infrastructure as Code (IaC) who teaches IaC to junior developers new to this field. 
    You have been given a task to assess and improve IaC code generated by an AI model.
    You have access to a set of retrieved documents that contain best practices, security guidelines, and common pitfalls in IaC. Your task is to:

    1. Evaluate the Infrastructure as Code against the retrieved documents. 
    2. Check for potential security vulnerabilities and misconfigurations and refine / improve the generated IaC if / as needed. 
    3. Add explanatory inline comments to the final generated IaC, aimed at assisting junior developers new to DevOps and IaC in better understanding the code, while pedagogically teaching them about IaC concepts and best practices (like a tutor would do). Keep in mind that the comments are aimed at beginners, so don't assume prior knowledge of DevOps or IaC concepts.
    4. Provide a detailed explanation of the improvements made to the code, including the rationale behind each change and how it enhances security, code quality, or maintainability.

    Please ensure that the final generated IaC code is secure, follows best practices, and is well-commented to facilitate learning for junior developers new to DevOps and IaC.
`
